from __future__ import annotations

PROJECT_DETAILS: dict[str, dict] = {
    "/projects/melrose-bathroom-layout/": {
        "name": "Melrose: A Bathroom Reworked From the Layout Out",
        "description": "A Melrose-area bathroom and lower-level project that moved the room through a wall, added a utility room and finished a new exercise room.",
        "image": "melrose-bathroom-after.jpg",
        "image_alt": "Completed Melrose-area bathroom with a wall-hung toilet, tiled shower, vanity and illuminated mirror",
        "neighbourhood": "Melrose area, London, Ontario",
        "status": "Completed",
        "services": ["Bathroom layout change", "Utility-room construction", "Drywall, ceiling and paint"],
    },
    "/projects/hyde-park-kitchen-renewal/": {
        "name": "Hyde Park: A Kitchen Renewed Without Starting Over",
        "description": "A Hyde Park kitchen renewal with refaced cabinetry, a new pantry, reconfigured appliances, dishwasher, backsplash, counters and sink.",
        "image": "hyde-park-kitchen-after.jpg",
        "image_alt": "Completed Hyde Park kitchen with refaced cabinetry, new counters, sink and backsplash",
        "neighbourhood": "Hyde Park, London, Ontario",
        "status": "Completed",
        "services": ["Cabinet refacing", "Pantry and appliance layout", "Backsplash, counters and sink"],
    },
    "/projects/blackfriars-leak-restoration/": {
        "name": "Blackfriars: A Small Leak That Needed a Much Bigger Plan",
        "description": "A Blackfriars leak investigation and restoration that uncovered mold, evidence of mice, structural concerns and knob-and-tube wiring.",
        "image": "blackfriars-restored-room.jpg",
        "image_alt": "Restored Blackfriars room with a smooth finished ceiling and painted walls",
        "neighbourhood": "Blackfriars, London, Ontario",
        "status": "Completed",
        "services": ["Investigation and project coordination", "Structural and trade coordination", "Drywall, ceiling and finish restoration"],
    },
    "/projects/medway-flooring-storage/": {
        "name": "Medway: More Storage, Better Flow and a Seamless Upper Level",
        "description": "An anonymous Medway flooring and storage project with carpet removal in three rooms, relocated and new closets, plank flooring, doors, casing and baseboards.",
        "image": "medway-floor-door-transition.jpg",
        "image_alt": "Completed Medway doorway with cool gray-brown plank flooring and a clean transition",
        "neighbourhood": "Medway, London, Ontario",
        "status": "Completed",
        "services": ["Flooring installation", "Closet and storage changes", "Doors, casing and baseboards"],
    },
    "/projects/westmount-porch-entry/": {
        "name": "A Westmount Porch and Entry, Modernized by Neighbours",
        "description": "A repeat Westmount customer’s porch and entry revitalization, shown through careful progress work, a daytime completion view and the finished exterior lighting at night.",
        "image": "westmount-porch-after-night.jpg",
        "image_alt": "Finished Westmount porch and entry illuminated at night",
        "neighbourhood": "Westmount, London, Ontario",
        "status": "Completed",
        "services": ["Exterior repairs", "Porch and entry finishing", "Handyman work"],
    },
    "/projects/westmount-1970s-transformation/": {
        "name": "Westmount: A Home Transformation Built in Thoughtful Phases",
        "description": "An ongoing Westmount transformation completed in phases around the clients’ timing and budget, including layout, flooring, lighting, kitchen work and one powder room.",
        "image": "westmount-transformation-blue-wall-flooring.jpg",
        "image_alt": "Completed Westmount living-space phase with plank flooring, pot lights and a deep-blue feature wall",
        "neighbourhood": "Westmount, London, Ontario",
        "status": "Project in progress",
        "services": ["Layout changes", "Kitchen work", "One powder-room renovation", "Flooring, lighting and finishing"],
    },
}

PROJECTS = [
    ("melrose-bathroom-after.jpg", "bathrooms structural", "Completed Melrose-area bathroom with vanity, illuminated mirror and tiled shower", "Melrose bathroom", "Completed layout change"),
    ("melrose-wall-hung-toilet-progress.jpg", "bathrooms structural", "Wall-hung toilet installed during the Melrose-area bathroom renovation", "Melrose fixture progress", "Installation in progress"),
    ("melrose-shower-tile-progress.jpg", "bathrooms", "Dark wall tile being installed in the Melrose-area shower", "Melrose shower tile", "Tile installation"),
    ("melrose-shower-toilet-detail.jpg", "bathrooms", "Completed Melrose-area tiled shower and wall-hung toilet", "Melrose finish detail", "Completed bathroom"),
    ("melrose-exercise-room-finishing.jpg", "drywall handyman", "Ceiling and paint finishing underway in the Melrose-area exercise room", "Melrose exercise room progress", "Drywall and paint"),
    ("melrose-exercise-room-after.jpg", "basements drywall", "Completed Melrose-area exercise room with smooth ceiling and painted walls", "Melrose exercise room", "Completed lower level"),
    ("hyde-park-kitchen-after.jpg", "kitchens", "Wide view of the completed Hyde Park kitchen", "Hyde Park kitchen", "Completed renewal"),
    ("hyde-park-pantry-and-appliance-layout.jpg", "kitchens handyman", "New pantry and reconfigured appliance wall in the Hyde Park kitchen", "Hyde Park pantry", "Storage and layout"),
    ("hyde-park-sink-and-dishwasher.jpg", "kitchens handyman", "New sink, counter and dishwasher in the Hyde Park kitchen", "Hyde Park sink wall", "Kitchen finish"),
    ("hyde-park-kitchen-preparation.jpg", "kitchens handyman", "Hyde Park kitchen protected during the update", "Hyde Park preparation", "Room protection"),
    ("hyde-park-backsplash-installation.jpg", "kitchens", "Backsplash tile being installed in the Hyde Park kitchen", "Hyde Park backsplash", "Tile installation"),
    ("blackfriars-first-opening.jpg", "restoration drywall", "Small initial ceiling opening during the Blackfriars leak investigation", "Blackfriars first opening", "Investigation"),
    ("blackfriars-investigation.jpg", "restoration drywall", "Protected investigation work after the Blackfriars ceiling was opened further", "Blackfriars investigation", "Investigation in progress"),
    ("blackfriars-structural-concern.jpg", "restoration structural", "Exposed framing documented during the Blackfriars investigation", "Blackfriars framing", "Existing condition"),
    ("blackfriars-rebuild.jpg", "restoration drywall insulation structural", "Blackfriars room during framing, insulation and rebuilding work", "Blackfriars rebuild", "Rebuilding in progress"),
    ("blackfriars-restored-room.jpg", "restoration drywall", "Restored Blackfriars room with smooth ceiling and painted walls", "Blackfriars restored room", "Completed restoration"),
    ("medway-finished-room.jpg", "flooring handyman", "Completed Medway room with cool gray-brown plank flooring and finished baseboards", "Medway finished room", "Completed flooring"),
    ("medway-finished-floor-detail.jpg", "flooring", "Close view of the completed Medway plank flooring and clean edge detail", "Medway floor detail", "Completed flooring"),
    ("hilltop-kitchen-wide.jpg", "kitchens", "Wide view of the completed Hilltop kitchen and island", "Hilltop kitchen", "Completed kitchen"),
    ("hilltop-kitchen-range.jpg", "kitchens", "Hilltop kitchen range wall and white cabinetry", "Hilltop range wall", "Kitchen detail"),
    ("hilltop-lower-level.jpg", "basements flooring", "Completed Hilltop lower-level living area with fireplace", "Hilltop lower level", "Completed basement"),
    ("hilltop-staircase.jpg", "basements flooring", "Finished Hilltop staircase with dark railing", "Hilltop staircase", "Flooring and stairs"),
    ("hilltop-green-tile-before.jpg", "bathrooms", "Hilltop upstairs bathroom with its original green-tile tub surround", "Hilltop bathroom before", "Before renovation"),
    ("hilltop-green-tile-after.jpg", "bathrooms", "Hilltop upstairs bathroom with a rebuilt marble-look tub surround", "Hilltop bathroom after", "Completed result"),
    ("hilltop-basement-bathroom-before.jpg", "bathrooms basements", "Hilltop basement bathroom before the shower, ceiling and finish renewal", "Hilltop basement bath before", "Before renovation"),
    ("hilltop-basement-bathroom-wide.jpg", "bathrooms basements", "Completed Hilltop basement bathroom with white vanity and glass shower", "Hilltop basement bath after", "Completed result"),
    ("bathroom-glass-block-before.jpg", "bathrooms", "Bathroom with a jetted tub and glass-block window before conversion", "Jetted-tub layout", "Bathroom before"),
    ("bathroom-glass-block-demolition.jpg", "bathrooms", "Tiled jetted-tub platform partly removed during demolition", "Tub-platform demolition", "Work in progress"),
    ("bathroom-glass-block-open-wall.jpg", "bathrooms insulation", "Tub removed with wall insulation and floor framing exposed", "Bathroom wall opened", "Structural preparation"),
    ("bathroom-walnut-vanity-after.jpg", "bathrooms flooring", "Completed tub-to-shower conversion with a walnut vanity, gray tile and sliding glass door", "Glass-shower conversion", "Completed bathroom"),
    ("kitchenette-before-wide.jpg", "kitchens commercial", "Office kitchen before cabinetry and repair work", "Office kitchen before", "Before renovation"),
    ("kitchenette-wall-plumbing-stage.jpg", "kitchens commercial drywall", "Office kitchen wall opened for plumbing and repair access", "Office kitchen wall access", "Work in progress"),
    ("kitchenette-cabinet-installation.jpg", "kitchens commercial handyman", "New office kitchen cabinet boxes and fronts during installation", "Office cabinet installation", "Installation in progress"),
    ("kitchenette-after-wide.jpg", "kitchens commercial", "Completed office kitchen with walnut-look cabinets and gray counter", "Office kitchen after", "Completed kitchen"),
    ("westmount-transformation-demolition.jpg", "structural drywall", "Westmount main-floor demolition and layout changes in progress", "Westmount layout work", "Ongoing transformation"),
    ("westmount-transformation-blue-wall-flooring.jpg", "flooring structural", "Completed Westmount living-space phase with plank flooring, pot lights and a deep-blue feature wall", "Westmount completed phase", "Flooring and lighting"),
    ("westmount-transformation-cabinet-install.jpg", "kitchens handyman", "Hekman Home Services crew installing kitchen cabinetry in the phased Westmount project", "Westmount cabinetry", "Kitchen in progress"),
    ("westmount-transformation-kitchen-current.jpg", "kitchens", "Current Westmount kitchen progress before the planned backsplash and final styling", "Westmount kitchen progress", "Work in progress"),
    ("westmount-porch-work-in-progress.jpg", "exterior handyman", "Exterior work in progress at an anonymous Westmount porch and entry", "Westmount porch progress", "Work in progress"),
    ("westmount-porch-after-night.jpg", "exterior handyman", "Finished Westmount porch and entry illuminated at night", "Westmount porch after", "Completed exterior"),
    ("project-016.jpg", "drywall", "Original textured ceiling and patch before smooth-ceiling work", "Popcorn ceiling before", "Before renovation"),
    ("project-017.jpg", "drywall", "Skim coating underway with the room protected", "Ceiling skim coat", "Surface preparation"),
    ("popcorn-ceiling-primer.jpg", "drywall", "Primer being rolled onto a smoothed ceiling", "Smooth ceiling primer", "Work in progress"),
    ("project-103.jpg", "exterior", "Completed elevated wood deck behind a brick home", "Elevated deck", "Completed exterior"),
    ("project-101.jpg", "exterior structural", "Deck framing and support-post structure", "Deck structure", "Structural preparation"),
    ("fence-after-1.jpg", "exterior", "Completed long-run wood privacy fence", "Privacy fence", "Completed exterior"),
    ("post-hole-digging.jpg", "exterior", "Post hole being dug by hand beside a residential property", "Post-hole preparation", "Site preparation"),
    ("post-hole-auger.jpg", "exterior", "Powered auger digging a post hole", "Powered auger work", "Site preparation"),
    ("project-045.jpg", "commercial", "Older box-style fluorescent fixtures before a fitness-space lighting upgrade", "Fitness lighting before", "Before upgrade"),
    ("project-049.jpg", "commercial", "Crew replacing commercial lighting from scaffolding and ladders", "Fitness lighting installation", "Installation in progress"),
    ("project-048.jpg", "commercial", "Fitness facility illuminated by the completed LED lighting upgrade", "Fitness lighting after", "Completed result"),
    ("salon-water-damage-2.jpg", "restoration commercial drywall", "Damaged salon ceiling opened to expose the affected construction", "Salon ceiling opened", "Commercial restoration"),
    ("salon-drywall-rebuild.jpg", "restoration commercial drywall", "Salon ceiling and wall surfaces being rebuilt with drywall and compound", "Salon rebuild", "Commercial restoration"),
    ("salon-after-1.jpg", "restoration commercial", "Working London salon returned to a bright finish after water damage", "Salon restored", "Completed restoration"),
]
PROJECT_GALLERY_PRIORITY = (
    "melrose-bathroom-after.jpg",
    "hyde-park-kitchen-after.jpg",
    "blackfriars-restored-room.jpg",
    "medway-finished-room.jpg",
    "hilltop-kitchen-wide.jpg",
    "hilltop-lower-level.jpg",
    "bathroom-walnut-vanity-after.jpg",
    "kitchenette-after-wide.jpg",
    "westmount-transformation-blue-wall-flooring.jpg",
    "westmount-porch-after-night.jpg",
    "project-103.jpg",
    "fence-after-1.jpg",
    "project-048.jpg",
    "salon-after-1.jpg",
    "melrose-exercise-room-after.jpg",
    "medway-finished-floor-detail.jpg",
    "hilltop-green-tile-after.jpg",
    "hilltop-basement-bathroom-wide.jpg",
)

