from __future__ import annotations

SERVICES: dict[str, dict] = {
    "bathrooms": {
        "name": "Bathroom Renovations",
        "card_name": "Bathrooms",
        "title": "Bathroom Renovations London ON | Hekman Home Services",
        "description": "Bathroom renovations in London, Ontario, including tile, waterproofing, vanities, fixtures, heated floors and tub-to-shower updates.",
        "hero": "bathroom-walnut-vanity-after.jpg",
        "hero_alt": "Completed tub-to-shower bathroom conversion with a walnut vanity and glass-block window",
        "position": "50% 52%",
        "lead": "Create a bathroom that works better every day—with careful preparation behind every visible finish.",
        "intro": "A successful bathroom renovation balances layout, water management, storage and finish details. We review the existing room, talk through priorities and build a clear scope around the condition of the space.",
        "scope": [
            ("Preparation & waterproofing", "Shower systems, substrate preparation and waterproofing are planned before tile and fixtures go in."),
            ("Tile & heated floors", "Wall tile, floor tile and heated-floor options can be coordinated into the room."),
            ("Fixtures & finish work", "Vanities, faucets, toilets, lighting, trim and paint-ready surfaces bring the room together."),
        ],
        "bullets": ["Full bathroom renovations", "Tub-to-shower conversions", "Shower and tub surrounds", "Tile and grout work", "Vanities, fixtures and storage", "Flooring, trim and finishing"],
        "gallery": [
            ("bathroom-glass-block-before.jpg", "Bathroom with a jetted tub and glass-block window before the tub-to-shower conversion", "Before: jetted-tub layout"),
            ("bathroom-glass-block-open-wall.jpg", "Jetted tub removed with the insulated wall and floor framing exposed", "During: opened wall and floor"),
            ("bathroom-walnut-vanity-after.jpg", "Completed tub-to-shower conversion with gray tile, a walnut vanity and sliding glass door", "After: glass shower conversion"),
            ("hilltop-green-tile-before.jpg", "Hilltop bathroom with its original green-tile tub surround", "Hilltop before: green-tile surround"),
            ("hilltop-green-tile-after.jpg", "Completed Hilltop tub surround with marble-look tile and dark accent trim", "Hilltop after: rebuilt tub surround"),
            ("hilltop-basement-bathroom-before.jpg", "Hilltop basement bathroom before the shower, ceiling and finishes were renewed", "Hilltop basement bathroom before"),
            ("hilltop-basement-bathroom-wide.jpg", "Completed Hilltop basement bathroom with white vanity and glass shower", "Hilltop basement bathroom after"),
            ("project-148.jpg", "Completed bathroom with glass shower enclosure", "Another glass shower renovation"),
            ("project-160.jpg", "Bathroom waterproofing system during construction", "Waterproofing in progress"),
        ],
        "faq": [
            ("Can you renovate the entire bathroom?", "Yes. Depending on the project, the scope can include demolition, preparation, waterproofing, tile, vanity, fixtures, flooring, trim and finishing."),
            ("Do you complete tub-to-shower conversions?", "Yes. The existing plumbing, structure and room layout are reviewed before the conversion is quoted."),
            ("Can heated flooring be included?", "Heated flooring can be considered where the floor system and overall project scope support it."),
        ],
        "related": ["kitchens", "flooring", "water-damage"],
    },
    "kitchens": {
        "name": "Kitchen Renovations",
        "card_name": "Kitchens",
        "title": "Kitchen Renovations London ON | Hekman Home Services",
        "description": "Kitchen renovations and upgrades in London, Ontario, including cabinet installation, backsplash, layout improvements and finish carpentry.",
        "hero": "hilltop-kitchen-wide.jpg",
        "hero_alt": "Completed Hilltop kitchen renovation with island seating",
        "position": "50% 52%",
        "lead": "Improve the heart of the home with a kitchen planned around storage, flow and the way your household lives.",
        "intro": "Kitchen work often connects cabinetry, plumbing, lighting, walls, flooring, tile and finishing. We look at the full room so the new elements feel integrated rather than added one at a time.",
        "scope": [
            ("Cabinets & layout", "Cabinet installation and practical layout changes can make better use of the available room."),
            ("Backsplash & surfaces", "Tile, wall repair and finishing help counters, cabinets and appliances sit cleanly together."),
            ("Lighting, plumbing & final details", "Pot lights, fixture and plumbing changes, trim, hardware, transitions and touch-ups are coordinated into the complete room."),
        ],
        "bullets": ["Kitchen renovations and updates", "Cabinet assembly and installation", "Backsplash installation", "Pot lights and lighting updates", "Plumbing and fixture changes", "Drywall, trim and finishing details"],
        "gallery": [
            ("hilltop-kitchen-wide.jpg", "Completed Hilltop kitchen with island seating", "Hilltop kitchen"),
            ("hilltop-kitchen-range.jpg", "White cabinetry and range wall in the Hilltop kitchen", "Cabinetry and range wall"),
            ("hilltop-kitchen-sink.jpg", "Sink, counter and backsplash in the completed Hilltop kitchen", "Sink and backsplash detail"),
            ("project-132.jpg", "Completed white kitchen with island seating", "Another completed kitchen"),
            ("kitchenette-before-wide.jpg", "Older kitchenette before cabinetry and repair work", "Before: existing kitchenette"),
            ("kitchenette-after-wide.jpg", "Completed kitchenette with walnut-look cabinets and gray counter", "Completed kitchenette"),
        ],
        "faq": [
            ("Do you install customer-supplied cabinets?", "Cabinet installation can be included after the cabinet system, measurements and site conditions are reviewed."),
            ("Can you update a kitchen without changing everything?", "Yes. A project can focus on cabinets, backsplash, flooring, repairs or finishing without requiring a full layout change."),
            ("Can you coordinate plumbing and pot lights?", "Yes. Kitchen scopes can include fixture plumbing, pot-light layouts and required trade coordination alongside cabinets, drywall and finish work."),
        ],
        "related": ["structural-layout", "flooring", "drywall-ceiling-repair"],
    },
    "basements": {
        "name": "Basement Renovations",
        "card_name": "Basements",
        "title": "Basement Renovations London ON | Hekman Home Services",
        "description": "Basement renovations in London, Ontario, including framing, drywall, ceilings, flooring, trim, storage and finished living spaces.",
        "hero": "hilltop-lower-level.jpg",
        "hero_alt": "Completed Hilltop lower-level renovation with fireplace and warm flooring",
        "position": "50% 60%",
        "lead": "Turn an unfinished or underused lower level into comfortable space that supports how your household lives.",
        "intro": "Basements can become family rooms, work areas, storage, guest space or a combination of uses. We help connect layout, surfaces and finishing into one practical renovation scope.",
        "planning_eyebrow": "Planning the lower level",
        "planning_title": "Start with how the whole floor should work.",
        "scope_title": "From framing to the final transition.",
        "scope_text": "The most useful basements connect layout, walls, ceilings, storage and flooring into one coordinated plan.",
        "scope": [
            ("Layout & framing", "Shape the lower level around living space, storage and the rooms the property needs."),
            ("Walls & ceilings", "Drywall, repairs and ceiling finishing move the space from rough construction to a clean interior."),
            ("Flooring & trim", "Flooring, doors, baseboards and transitions connect the basement with the rest of the home."),
        ],
        "bullets": ["Basement finishing", "Framing and room layouts", "Drywall and ceiling work", "Flooring installation", "Doors, trim and storage", "Focused basement repairs"],
        "gallery": [
            ("hilltop-lower-level.jpg", "Completed Hilltop lower-level living space with fireplace", "Hilltop lower level"),
            ("pond-mills-basement-floor-after.jpg", "Completed Pond Mills lower-level room with light plank flooring and finished baseboards", "Pond Mills completed floor"),
            ("project-067.jpg", "Finished basement with warm wood flooring", "Finished living space"),
            ("hilltop-staircase.jpg", "Finished Hilltop staircase with dark railing", "Stair and railing detail"),
            ("hilltop-entry.jpg", "Finished lower-level entry and flooring transition", "Entry and transition"),
        ],
        "faq": [
            ("Can you finish an unfinished basement?", "Basement scopes can include framing, drywall, flooring, doors, trim and other finish work, subject to existing conditions and permit requirements."),
            ("Can a bathroom or kitchenette be included?", "Those features can be considered when plumbing, electrical and permit requirements are addressed in the project plan."),
            ("Do you take on partial basement projects?", "Yes. Work can focus on one room, flooring, ceilings, storage or another specific improvement."),
        ],
        "related": ["flooring", "drywall-ceiling-repair", "structural-layout"],
    },
    "flooring": {
        "name": "Flooring Installation",
        "card_name": "Flooring",
        "title": "Flooring Installation London ON | Hekman Home Services",
        "description": "Carpet, vinyl plank, laminate, hardwood and tile flooring installation in London, Ontario, with subfloor preparation and finish trim.",
        "hero": "project-072.jpg",
        "hero_alt": "Completed plank flooring installation in a renovated room",
        "position": "50% 60%",
        "lead": "Carpet, vinyl, laminate, hardwood and tile—installed with the right preparation underneath and clean details at every edge.",
        "intro": "Flooring changes the feel of an entire room. We work with carpet, vinyl plank, laminate, hardwood and tile, reviewing the existing surface, movement between rooms and the details needed at walls, doors, stairs and adjoining finishes.",
        "planning_eyebrow": "Preparation before installation",
        "planning_title": "A better floor starts underneath.",
        "scope_title": "Clean lines from room to room.",
        "scope_text": "Material choice matters, but preparation, layout, thresholds, baseboards and stairs determine how complete the result feels.",
        "scope": [
            ("Removal & preparation", "Existing carpet or hard flooring can be removed, and visible subfloor conditions and transitions are reviewed before installation."),
            ("Material-specific installation", "Carpet, vinyl plank, laminate, hardwood and tile each receive the layout and installation approach the selected material requires."),
            ("Trim & transitions", "Baseboards, nosings, thresholds and doorway details complete the installation."),
        ],
        "bullets": ["Carpet installation and removal", "Vinyl plank and laminate", "Hardwood and engineered wood", "Tile flooring", "Subfloor preparation", "Transitions, stairs and finish trim"],
        "gallery": [
            ("medway-floor-door-transition.jpg", "Completed Medway door, cool gray-brown plank flooring and clean transition", "Medway completed transition"),
            ("pond-mills-kitchen-floor-after.jpg", "Completed light plank flooring carried into a Pond Mills kitchen", "Pond Mills completed kitchen floor"),
            ("pond-mills-kitchen-floor-before.jpg", "Original narrow warm-toned flooring in the same Pond Mills kitchen", "Pond Mills before flooring"),
            ("medway-floor-installation.jpg", "Plank flooring being installed in the Medway upper level", "Medway installation in progress"),
            ("project-063.jpg", "Tile flooring at a bright patio entry", "Tile and transition work"),
            ("project-043.jpg", "Dark wood flooring in a finished room", "Wood flooring finish"),
            ("project-066.jpg", "Finished staircase with wood treads", "Stair finish detail"),
            ("project-060.jpg", "Click flooring installation beside a finished wall", "Flooring installation detail"),
        ],
        "faq": [
            ("Do you remove the existing floor?", "Removal and disposal can be included where needed and will be identified in the quote."),
            ("Can you repair the subfloor first?", "Visible subfloor concerns can be reviewed and included in the scope before the finished flooring is installed."),
            ("Do you complete baseboards and transitions?", "Yes. Trim, thresholds and transitions can be included so the room feels finished."),
        ],
        "related": ["basements", "kitchens", "water-damage"],
    },
    "drywall-ceiling-repair": {
        "name": "Drywall & Ceiling Repair",
        "card_name": "Drywall & Ceilings",
        "title": "Drywall & Ceiling Repair London ON | Hekman Home Services",
        "description": "Drywall, ceiling and related insulation work in London, Ontario, including replacement, taping, mudding, sanding and paint-ready finishes.",
        "hero": "project-014.jpg",
        "hero_alt": "Smooth repaired ceiling in a finished room",
        "position": "50% 58%",
        "lead": "Repair damaged walls and ceilings with careful preparation and a smooth, paint-ready finish.",
        "intro": "Good drywall work should disappear into the room. We assess the damaged area, remove loose or affected material where needed, address accessible insulation within the repair scope and build the finish in controlled stages.",
        "scope": [
            ("Open & assess", "The damaged area is reviewed so loose material and the repair boundary can be handled properly."),
            ("Patch & finish", "New board, tape and compound are applied in the stages required for the repair."),
            ("Prepare for paint", "Sanding and final touch-ups create a clean surface for primer and paint."),
        ],
        "bullets": ["Wall and ceiling patches", "Drywall replacement", "Taping and mudding", "Ceiling repairs", "Insulation work in opened walls or ceilings", "Primer, painting and finish restoration"],
        "gallery": [
            ("project-011.jpg", "Drywall finishing in progress on walls and ceiling", "Finishing in progress"),
            ("project-015.jpg", "Ceiling patch and compound work", "Ceiling repair"),
            ("project-014.jpg", "Completed smooth ceiling in a finished room", "Completed ceiling"),
            ("project-010.jpg", "Protected room prepared for drywall finishing", "Room protection and preparation"),
            ("insulation-open-wall.jpg", "Opened wall and ceiling with insulation exposed during renovation", "Insulation and wall access"),
            ("insulation-drywall-stage.jpg", "Drywall being installed over insulated wall cavities", "Insulation and drywall stage"),
        ],
        "faq": [
            ("Can you repair damage after another trade opens a wall?", "Yes. Openings left after plumbing, electrical or other repair work can be reviewed for patching and finishing."),
            ("Will the repair be ready for paint?", "The quote will identify whether the scope ends at a sanded, paint-ready finish or includes primer and paint."),
            ("Can several patches be completed together?", "Yes. Multiple repair areas can often be grouped into one project after they are reviewed."),
        ],
        "related": ["popcorn-ceiling-removal", "water-damage", "basements"],
    },
    "popcorn-ceiling-removal": {
        "name": "Popcorn Ceiling Removal",
        "card_name": "Popcorn Ceilings",
        "title": "Popcorn Ceiling Removal London ON | Hekman Home Services",
        "description": "Popcorn ceiling removal in London, Ontario, with preparation, scraping, skim coating, sanding and smooth ceiling finishing.",
        "hero": "project-016.jpg",
        "hero_alt": "Textured ceiling documented before smooth-ceiling finishing",
        "position": "50% 42%",
        "lead": "Replace a dated textured ceiling with a cleaner, brighter surface that changes the feel of the whole room.",
        "intro": "Removing ceiling texture is a preparation-heavy project. The room is protected, the existing surface is assessed and the ceiling is finished through the stages needed for a smooth result.",
        "scope": [
            ("Protect the room", "Floors, walls and fixed items are covered before ceiling work begins."),
            ("Remove & skim", "Texture is removed where appropriate and the surface is repaired or skim coated as required."),
            ("Sand & finish", "The ceiling is sanded and checked before the agreed primer or paint finish is completed."),
        ],
        "bullets": ["Popcorn ceiling removal", "Room and floor protection", "Ceiling repairs", "Skim coating", "Sanding and smoothing", "Primer and paint options"],
        "gallery": [
            ("project-016.jpg", "Original textured ceiling and a patched opening before finishing", "Before: textured ceiling"),
            ("popcorn-ceiling-sander.jpg", "Dust-covered drywall sander used during popcorn ceiling removal", "Dust-controlled sanding equipment"),
            ("project-017.jpg", "Ceiling skim coating underway with the room protected", "Skim-coat stage"),
            ("popcorn-ceiling-primer.jpg", "Primer being rolled onto the smoothed ceiling", "Primer and finish stage"),
        ],
        "faq": [
            ("Does every textured ceiling come off the same way?", "No. Paint, previous repairs and the underlying surface can change the removal and finishing process."),
            ("How is the room protected?", "The required floor, wall and fixture protection is planned as part of the project scope."),
            ("Can the ceiling be primed and painted too?", "Yes. Primer and paint can be included so the ceiling is fully finished."),
        ],
        "related": ["drywall-ceiling-repair", "basements", "water-damage"],
    },
    "decks-exterior": {
        "name": "Decks & Exterior Work",
        "card_name": "Decks & Exterior",
        "title": "Decks & Exterior Work London ON | Hekman Home Services",
        "description": "Deck construction, railings, fences and exterior repair services in London, Ontario and surrounding communities.",
        "hero": "project-103.jpg",
        "hero_alt": "Completed elevated wood deck at a residential property",
        "position": "50% 52%",
        "lead": "Build, repair or improve outdoor spaces with attention to structure, safe access and a clean exterior finish.",
        "intro": "Exterior work has to respond to weather, existing structure and how people use the property. We review access, site conditions and the full scope—whether that is a deck, fence, gate, railing, post or focused repair—before work begins.",
        "planning_eyebrow": "Planning for the property",
        "planning_title": "Built for weather, access and everyday use.",
        "scope_title": "Exterior work that connects.",
        "scope_text": "Decks, guards, stairs, fences and posts need to work with the existing structure, grade and access around the property.",
        "scope": [
            ("Deck structures", "New construction and replacement work are planned around the property, access and required approvals."),
            ("Railings & stairs", "Steps, guards, railings and transitions are considered as part of safe everyday use."),
            ("Fences, gates & posts", "Privacy fencing, gates, post replacement and post-hole work can be planned around access, grade and the intended layout."),
        ],
        "bullets": ["Deck construction and replacement", "Deck repairs", "Stairs, railings and guards", "Privacy fences and gates", "Post-hole digging and auger work", "Posts, trim and focused repairs"],
        "gallery": [
            ("project-103.jpg", "Completed elevated deck behind a brick home", "Completed deck"),
            ("project-104.jpg", "Completed row of renewed rear decks at an anonymous multi-unit property", "Completed multi-unit deck row"),
            ("multi-unit-decks-before.jpg", "Weathered connected rear decks before renewal work", "Before deck renewal"),
            ("project-101.jpg", "Rear deck opened during construction work", "Deck work in progress"),
            ("fence-after-1.jpg", "Completed long-run wood privacy fence", "Privacy fence"),
            ("fence-post-layout-progress.jpg", "Aligned wood fence posts set during a separate installation", "Fence-post layout in progress"),
            ("fence-post-auger-installation.jpg", "Powered auger preparing a fence-post hole at the same installation", "Fence-post auger work"),
        ],
        "faq": [
            ("Do deck projects require permits?", "Some do. Requirements depend on height, size, attachment and local rules. Permit needs are identified during planning."),
            ("Can you replace railings or stairs without replacing the whole deck?", "Focused repairs or replacements can be considered after the existing structure is assessed."),
            ("Do you complete exterior repair lists?", "Yes. Multiple compatible exterior items can be reviewed and grouped into one quote."),
        ],
        "related": ["structural-layout", "water-damage", "commercial"],
    },
    "water-damage": {
        "name": "Restoration & Damage Repairs",
        "card_name": "Restoration & Damage",
        "title": "Water Damage & Restoration Repairs London ON | Hekman",
        "description": "Restorative construction and water-damage repairs in London, Ontario, including damaged drywall, ceilings, flooring, trim, insulation and finish work.",
        "hero": "salon-restored-wall.jpg",
        "hero_alt": "Completed wall and ceiling restoration in an anonymous London salon",
        "position": "50% 45%",
        "lead": "When damage interrupts a home or business, rebuild the affected space with one clear plan—from opening the problem area to restoring the final finish.",
        "intro": "Restoration work rarely begins as a planned renovation. It may start with a leak, a damaged ceiling, an opened wall or a repair that left the room unfinished. Once the source and any immediate safety concerns have been addressed, Hekman Home Services can coordinate the construction work that puts the affected space back together.",
        "scope": [
            ("Understand what was affected", "Document the visible damage and identify which walls, ceilings, floors, insulation or finishes belong in the repair scope."),
            ("Open, repair & rebuild", "Remove affected finishes where required, complete the agreed rebuilding work and coordinate the connected surfaces in the right order."),
            ("Make the space feel whole again", "Drywall, trim, transitions, primer and paint bring the repair back into the surrounding home or business."),
        ],
        "bullets": ["Repairs after leaks and water damage", "Damaged drywall and ceiling rebuilding", "Insulation and wall-cavity restoration", "Flooring, trim and baseboard repair", "Residential and commercial restoration", "Primer, paint and final finish work"],
        "gallery": [
            ("salon-moisture-investigation.jpg", "Moisture meter documenting an affected trim area in an anonymous London salon", "Moisture investigation"),
            ("salon-wall-ceiling-rebuild.jpg", "Wall and ceiling surfaces being rebuilt in an anonymous London salon", "Wall and ceiling rebuilding"),
            ("salon-restored-wall.jpg", "Completed wall repair in an anonymous London salon", "Completed wall restoration"),
            ("salon-after-1.jpg", "Broader view of the salon interior after repair work", "Salon interior after repairs"),
        ],
        "faq": [
            ("Do you stop the active leak?", "The source should be identified and corrected first. Our scope can focus on removal, repair and rebuilding afterward."),
            ("Can drywall and flooring be repaired together?", "Yes. One quote can include several affected finishes where appropriate."),
            ("Can you review an insurance repair scope?", "We can review the requested work and prepare our own quote based on the actual site conditions and repair scope."),
        ],
        "related": ["drywall-ceiling-repair", "commercial", "handyman-repairs"],
    },
    "commercial": {
        "name": "Commercial Maintenance & Repairs",
        "card_name": "Commercial Work",
        "title": "Commercial Maintenance London ON | Hekman Home Services",
        "description": "Commercial maintenance and repairs in London, Ontario, including salon, fitness, retail, office-kitchen, drywall, lighting and repair work.",
        "hero": "salon-restored-wall.jpg",
        "hero_alt": "Completed wall and ceiling restoration in an anonymous London salon",
        "position": "50% 56%",
        "lead": "Responsive repair and improvement work for salons, fitness facilities, offices, retail, rentals and managed properties.",
        "intro": "Commercial spaces need repairs completed with a clear scope, awareness of customers and staff, and respect for day-to-day operations. Hekman Home Services can address one urgent repair, a tenant improvement or a grouped maintenance list across drywall, ceilings, pot lights, plumbing fixtures, painting, doors, trim, kitchenettes and other compatible work.",
        "scope": [
            ("Repair lists", "Drywall, trim, doors, fixtures and other compatible items can be grouped into one scope."),
            ("Occupied-space improvements", "Finish updates, lighting-related ceiling work and layout repairs can support salons, fitness facilities, retail and office spaces."),
            ("Property maintenance", "Business owners, landlords and property managers can consolidate several repair needs into one practical project quote."),
        ],
        "bullets": ["Commercial drywall and water-damage repairs", "Pot lights and ceiling finish work", "Salon, retail, office-kitchen and fitness-space improvements", "Plumbing fixtures, doors, trim and painting", "Grouped maintenance lists", "Rental and managed-property repairs"],
        "gallery": [
            ("salon-restored-wall.jpg", "Completed wall and ceiling restoration in an anonymous London salon", "Salon commercial restoration"),
            ("project-045.jpg", "Original box-style fluorescent fixtures in a London fitness facility", "Before: older light fixtures"),
            ("project-049.jpg", "Hekman Home Services team replacing commercial lighting from scaffolding and ladders", "During: lighting replacement"),
            ("project-048.jpg", "Fitness facility illuminated by the completed LED lighting upgrade", "After: LED lighting"),
            ("kitchenette-before-wide.jpg", "Dated office kitchen before the renovation", "Office kitchen before"),
            ("kitchenette-after-wide.jpg", "Completed office kitchen with new cabinets, counter and sink", "Office kitchen complete"),
        ],
        "faq": [
            ("Do you work in occupied commercial spaces?", "Yes, when the scope, access and scheduling requirements make it practical. We discuss ways to reduce disruption."),
            ("Can several small repairs be grouped together?", "Yes. Grouping compatible maintenance items can make the work more efficient."),
            ("Do you work with landlords and property managers?", "Commercial and rental-property repair work can be quoted for owners and managers."),
        ],
        "related": ["drywall-ceiling-repair", "structural-layout", "water-damage"],
    },
    "handyman-repairs": {
        "name": "Handyman Work & Home Repairs",
        "card_name": "Handyman & Repairs",
        "title": "Handyman & Home Repairs London ON | Hekman Home Services",
        "description": "Handyman and home repair services in London, Ontario, including doors, trim, plumbing fixtures, painting, drywall patching and grouped repair lists.",
        "hero": "project-027.jpg",
        "hero_alt": "Doorway and trim work during a residential repair project",
        "position": "50% 48%",
        "lead": "Take care of the repairs that keep getting postponed—from doors and trim to drywall patches, paint and bathroom fixtures.",
        "intro": "Not every project is a full renovation. Hekman Home Services can group compatible repairs into one practical scope, making it easier to address the small problems and finish details that affect how a home works every day.",
        "scope": [
            ("Doors & trim", "Interior doors, hardware, casing, baseboards and focused carpentry repairs can be reviewed together."),
            ("Patches & paint", "Drywall damage, ceiling patches, surface preparation and painting can restore worn or opened areas."),
            ("Fixtures & repair lists", "Bathroom and kitchen plumbing fixtures, caulking, hardware and other compatible maintenance items can be grouped into one visit."),
        ],
        "bullets": ["Interior door and hardware repairs", "Baseboards, casing and trim", "Drywall and ceiling patching", "Painting and touch-ups", "Bathroom and kitchen plumbing fixtures", "Grouped handyman and maintenance lists"],
        "gallery": [
            ("westmount-porch-after-day.jpg", "Finished anonymous Westmount porch and entry in daylight", "Westmount porch and entry"),
            ("medway-floor-door-transition.jpg", "Completed Medway door, flooring and transition detail", "Door and flooring finish"),
            ("project-032.jpg", "Drywall patching and compound on an interior wall", "Drywall patching"),
            ("project-140.jpg", "Painting and finishing work in a bathroom", "Painting and finish work"),
            ("project-139.jpg", "Bathroom toilet and flooring installation detail", "Bathroom fixture work"),
            ("bathroom-walnut-vanity-after.jpg", "Completed bathroom with walnut vanity, fixtures and glass shower", "Bathroom finish details"),
        ],
        "faq": [
            ("Can I send a list of several repairs?", "Yes. Photos and a room-by-room list help us identify which compatible items can be completed in one scope."),
            ("Do you handle plumbing repairs?", "Fixture replacement and compatible bathroom or kitchen plumbing repairs can be reviewed, with licensed trade coordination used where the work requires it."),
            ("Can patching and painting be completed together?", "Yes. Drywall patching, surface preparation, primer and painting can be combined when that is the right finish for the repair."),
        ],
        "related": ["drywall-ceiling-repair", "bathrooms", "commercial"],
    },
    "structural-layout": {
        "name": "Structural & Layout Changes",
        "card_name": "Structural & Layout",
        "title": "Structural & Layout Changes London ON | Hekman Home Services",
        "description": "Framing, wall openings, closet builds and layout changes for renovation projects in London, Ontario.",
        "hero": "westmount-transformation-demolition.jpg",
        "hero_alt": "Westmount main-floor demolition and layout changes in progress",
        "position": "50% 50%",
        "lead": "Change how rooms connect, improve storage and make an existing layout work better for everyday life.",
        "intro": "Layout work often affects framing, drywall, flooring and adjacent finishes. We assess what is existing and work with engineers and designers where the project requires structural direction, drawings, permits or a coordinated design plan.",
        "scope": [
            ("Openings & flow", "Doorways and room connections can be reshaped where the structure, engineering and project plan allow."),
            ("Framing & storage", "New partitions, closets and storage areas can improve how the available space is used."),
            ("Repair & finish", "Drywall, trim and nearby finishes are coordinated so the change feels integrated."),
        ],
        "bullets": ["Wall openings and revisions", "Interior framing", "Engineer and designer coordination", "Closet, storage and doorway changes", "Drywall and finish restoration", "Permit and specialty-trade coordination"],
        "gallery": [
            ("westmount-transformation-demolition.jpg", "Westmount main-floor demolition and layout changes in progress", "Westmount layout phase"),
            ("medway-closet-before.jpg", "Medway room with carpet and the new closet opening visible", "Medway closet layout"),
            ("medway-closet-relocation-progress.jpg", "Former Medway closet opening closed and prepared as a seamless wall", "Closet opening relocated"),
            ("medway-floor-door-transition.jpg", "Completed Medway doorway, flooring and clean transition", "Connected doors, trim and flooring"),
        ],
        "faq": [
            ("Can you remove a wall?", "Potential wall changes must be assessed first. Structural walls require appropriate engineering, permits and supporting work."),
            ("Can you build a new closet?", "Yes. Framing, drywall, doors and trim can be included in the scope."),
            ("Do layout changes require permits?", "Some do. Requirements depend on structural, plumbing, electrical and other systems affected by the work."),
        ],
        "related": ["kitchens", "basements", "drywall-ceiling-repair"],
    },
}
SERVICE_DISPLAY_ORDER = [
    "bathrooms",
    "drywall-ceiling-repair",
    "kitchens",
    "flooring",
    "basements",
    "handyman-repairs",
    "decks-exterior",
    "water-damage",
    "commercial",
    "structural-layout",
    "popcorn-ceiling-removal",
]
SERVICE_CARD_VARIANTS: dict[str, list[tuple[str, str]]] = {
    "bathrooms": [
        ("hilltop-green-tile-after.jpg", "Completed Hilltop bathroom with a marble-look tub surround"),
        ("hilltop-basement-bathroom-wide.jpg", "Completed Hilltop basement bathroom with a glass shower"),
        ("project-148.jpg", "Completed bathroom with a glass shower enclosure"),
        ("project-161.jpg", "Completed bathroom with a warm wood vanity and black fixtures"),
        ("bathroom-walnut-vanity-after.jpg", "Completed tub-to-shower conversion with a walnut vanity"),
    ],
    "drywall-ceiling-repair": [
        ("blackfriars-restored-room.jpg", "Restored Blackfriars room with a smooth finished ceiling and painted walls"),
        ("project-014.jpg", "Completed smooth ceiling after repair and finishing"),
        ("project-011.jpg", "Drywall and ceiling finishing in progress"),
        ("project-007.jpg", "Drywall preparation during an interior renovation"),
        ("insulation-drywall-stage.jpg", "Drywall being installed over insulated wall cavities"),
        ("project-152.jpg", "Wall-board rebuilding around a frosted bathroom window"),
    ],
    "kitchens": [
        ("hilltop-kitchen-range.jpg", "Completed Hilltop kitchen cabinetry and range wall"),
        ("project-132.jpg", "Completed white kitchen with island seating"),
        ("kitchenette-after-wide.jpg", "Completed office kitchen with new cabinetry and counter"),
        ("project-114.jpg", "Completed kitchen renovation with bright cabinetry"),
        ("hilltop-kitchen-sink.jpg", "Completed Hilltop kitchen sink and backsplash detail"),
    ],
    "flooring": [
        ("pond-mills-kitchen-floor-after.jpg", "Completed light plank flooring carried into a Pond Mills kitchen"),
        ("project-043.jpg", "Dark wood flooring in a completed room"),
        ("project-042.jpg", "New plank flooring carried through a kitchen"),
        ("project-038.jpg", "Engineered wood flooring installation in progress"),
        ("project-072.jpg", "Completed plank flooring in a renovated room"),
        ("hardwood-installation-detail.jpg", "Hardwood flooring installation detail"),
    ],
    "basements": [
        ("pond-mills-basement-floor-after.jpg", "Completed Pond Mills lower-level room with light plank flooring and finished baseboards"),
        ("project-067.jpg", "Finished basement living space with warm wood flooring"),
        ("project-072.jpg", "Completed plank flooring in a finished lower-level room"),
        ("hilltop-lower-level.jpg", "Completed Hilltop lower level with fireplace and warm flooring"),
        ("project-044.jpg", "Finished basement with new resilient plank flooring"),
    ],
    "handyman-repairs": [
        ("project-035.jpg", "Completed room repairs, flooring and finish work"),
        ("medway-finished-room.jpg", "Completed Medway room with new flooring, baseboards and connected finish work"),
        ("project-140.jpg", "Interior closet and storage work in progress"),
        ("project-027.jpg", "Interior doorway and trim work during renovation"),
        ("project-108.jpg", "Cabinet installation and interior finish work"),
    ],
    "decks-exterior": [
        ("project-103.jpg", "Completed elevated wood deck at a residential property"),
        ("project-104.jpg", "Completed row of renewed rear decks at an anonymous multi-unit property"),
        ("fence-after-1.jpg", "Completed long-run wood privacy fence"),
        ("fence-post-auger-installation.jpg", "Powered auger preparing a fence-post hole"),
        ("project-101.jpg", "Deck framing and exterior support structure"),
        ("project-100.jpg", "Completed deck and guard structure at an anonymous multi-unit property"),
    ],
    "water-damage": [
        ("salon-restored-wall.jpg", "Completed wall repair in an anonymous London salon"),
        ("blackfriars-restored-room.jpg", "Restored Blackfriars room after investigation and rebuilding"),
        ("salon-moisture-investigation.jpg", "Moisture investigation at an affected salon trim area"),
        ("salon-wall-ceiling-rebuild.jpg", "Salon wall and ceiling surfaces being rebuilt"),
    ],
    "commercial": [
        ("project-048.jpg", "Commercial fitness space after an LED lighting upgrade"),
        ("kitchenette-after-wide.jpg", "Completed staff kitchen in a London commercial property"),
        ("salon-restored-wall.jpg", "Completed wall and ceiling restoration in an anonymous London salon"),
        ("project-049.jpg", "Commercial lighting replacement in progress from scaffolding and ladders"),
        ("salon-wall-ceiling-rebuild.jpg", "Anonymous London salon wall and ceiling repair in progress"),
    ],
    "structural-layout": [
        ("westmount-transformation-blue-wall-flooring.jpg", "Completed Westmount living-space phase after layout, lighting and flooring work"),
        ("medway-finished-room.jpg", "Completed Medway room after connected flooring and storage changes"),
        ("westmount-transformation-demolition.jpg", "Westmount demolition and layout changes in progress"),
        ("medway-closet-relocation-progress.jpg", "Former Medway closet opening closed for the new layout"),
        ("project-138.jpg", "Framed wall opening during an interior renovation"),
        ("medway-closet-before.jpg", "Medway room with the new closet opening visible"),
    ],
    "popcorn-ceiling-removal": [
        ("project-016.jpg", "Original popcorn-textured ceiling before removal and smooth-ceiling finishing"),
        ("popcorn-ceiling-primer.jpg", "Primer being applied to a newly smoothed ceiling"),
        ("popcorn-ceiling-sander.jpg", "Drywall sander used during popcorn ceiling removal"),
        ("project-017.jpg", "Ceiling skim coating underway in a protected room"),
        ("project-014.jpg", "Completed smooth ceiling after texture removal and finish work"),
        ("project-015.jpg", "Ceiling surface correction and compound work"),
    ],
}
