from __future__ import annotations

PROJECT_DETAILS: dict[str, dict] = {
    "/projects/melrose-bathroom-layout/": {
        "name": "Melrose: A Bathroom Reworked From the Layout Out",
        "description": "A Melrose-area bathroom and lower-level project that moved the room through a wall, added a utility room and finished a new exercise room.",
        "image": "melrose-bathroom-after.jpg",
        "image_alt": "Completed Melrose-area bathroom with a wall-hung toilet, tiled shower, vanity and illuminated mirror",
        "neighbourhood": "Melrose area, London, Ontario",
        "status": "Completed",
        "services": ["Bathroom layout change", "Utility-room construction", "Drywall, ceiling and paint"],
    },
    "/projects/hyde-park-kitchen-renewal/": {
        "name": "Hyde Park: A Kitchen Renewed Without Starting Over",
        "description": "A Hyde Park kitchen renewal with refaced cabinetry, a new pantry, reconfigured appliances, dishwasher, backsplash, counters and sink.",
        "image": "hyde-park-kitchen-after.jpg",
        "image_alt": "Completed Hyde Park kitchen with refaced cabinetry, new counters, sink and backsplash",
        "neighbourhood": "Hyde Park, London, Ontario",
        "status": "Completed",
        "services": ["Cabinet refacing", "Pantry and appliance layout", "Backsplash, counters and sink"],
    },
    "/projects/blackfriars-leak-restoration/": {
        "name": "Blackfriars: A Small Leak That Needed a Much Bigger Plan",
        "description": "A Blackfriars leak investigation and restoration that uncovered mold, evidence of mice, structural concerns and knob-and-tube wiring.",
        "image": "blackfriars-restored-room.jpg",
        "image_alt": "Restored Blackfriars room with a smooth finished ceiling and painted walls",
        "neighbourhood": "Blackfriars, London, Ontario",
        "status": "Completed",
        "services": ["Investigation and project coordination", "Structural and trade coordination", "Drywall, ceiling and finish restoration"],
    },
    "/projects/hilltop-home-transformation/": {
        "name": "Hilltop: One Home, One Clear Point of View",
        "description": "A whole-home Hilltop transformation in London connecting the kitchen, two bathrooms, lower level, entry, stairs, flooring and finish details.",
        "image": "hilltop-kitchen-wide.jpg",
        "image_alt": "Wide view of the completed Hilltop kitchen with white cabinetry, a large island and warm wood flooring",
        "neighbourhood": "Hilltop area, London, Ontario",
        "status": "Completed",
        "services": ["Kitchen renovation", "Bathroom renovations", "Lower-level, flooring and finish work"],
    },
    "/projects/kitchen-renewal/": {
        "name": "Office Kitchen: A Compact Staff Space Rebuilt to Work Better",
        "description": "A London office kitchen renewal documented from the original room through plumbing access and cabinet installation to the completed staff space.",
        "image": "kitchenette-after-wide.jpg",
        "image_alt": "Completed London office kitchen with walnut-look cabinetry, gray counter, sink and compact appliances",
        "neighbourhood": "London, Ontario",
        "status": "Completed",
        "services": ["Commercial kitchen renewal", "Cabinet and counter installation", "Drywall, plumbing access and finishing"],
    },
    "/projects/popcorn-ceiling-transformation/": {
        "name": "London Popcorn Ceiling Transformation",
        "description": "A London popcorn ceiling project documented from the original texture through sanding, skim coating, surface checks and primer.",
        "image": "project-016.jpg",
        "image_alt": "Original textured ceiling and an existing patch before smooth-ceiling work began",
        "neighbourhood": "London, Ontario",
        "status": "Completed",
        "services": ["Popcorn ceiling removal", "Skim coating and surface correction", "Primer and paint preparation"],
    },
    "/projects/glass-block-bathroom-conversion/": {
        "name": "From Jetted Tub to Glass Shower",
        "description": "A London-area bathroom conversion documented from the original jetted tub through demolition and open-wall work to the completed tiled shower.",
        "image": "bathroom-walnut-vanity-after.jpg",
        "image_alt": "Completed bathroom with a gray tiled shower, sliding glass enclosure, walnut vanity and original glass-block window",
        "neighbourhood": "London area, Ontario",
        "status": "Completed",
        "services": ["Tub-to-shower conversion", "Wall and floor access", "Tile, glass enclosure and finish work"],
    },
    "/projects/medway-flooring-storage/": {
        "name": "Medway: More Storage, Better Flow and a Seamless Upper Level",
        "description": "An anonymous Medway flooring and storage project with carpet removal in three rooms, relocated and new closets, plank flooring, doors, casing and baseboards.",
        "image": "medway-floor-door-transition.jpg",
        "image_alt": "Completed Medway doorway with cool gray-brown plank flooring and a clean transition",
        "neighbourhood": "Medway, London, Ontario",
        "status": "Completed",
        "services": ["Flooring installation", "Closet and storage changes", "Doors, casing and baseboards"],
    },
    "/projects/westmount-porch-entry/": {
        "name": "A Westmount Porch and Entry, Modernized by Neighbours",
        "description": "A repeat Westmount customer’s porch and entry revitalization, documented through progress work, daylight completion and finished exterior lighting.",
        "image": "westmount-porch-after-night.jpg",
        "image_alt": "Finished Westmount porch and entry illuminated at night",
        "neighbourhood": "Westmount, London, Ontario",
        "status": "Completed",
        "services": ["Exterior repairs", "Porch and entry finishing", "Handyman work"],
    },
    "/projects/westmount-1970s-transformation/": {
        "name": "Westmount: A Home Transformation Built in Thoughtful Phases",
        "description": "An ongoing Westmount transformation phased around timing and budget, including layout, flooring, lighting, kitchen work and one powder room.",
        "image": "westmount-transformation-blue-wall-flooring.jpg",
        "image_alt": "Completed Westmount living-space phase with plank flooring, pot lights and a deep-blue feature wall",
        "neighbourhood": "Westmount, London, Ontario",
        "status": "Project in progress",
        "services": ["Layout changes", "Kitchen work", "One powder-room renovation", "Flooring, lighting and finishing"],
    },
    "/projects/commercial-salon-repair/": {
        "name": "London Salon: Moisture Investigation and Interior Restoration",
        "description": "An anonymous London salon restoration from moisture investigation and affected-material removal through wall-and-ceiling rebuilding and the completed finish.",
        "image": "salon-restored-wall.jpg",
        "image_alt": "Completed repaired wall beneath cage lights in an anonymous London salon",
        "neighbourhood": "London, Ontario",
        "status": "Completed",
        "services": ["Moisture investigation", "Wall and ceiling rebuilding", "Drywall and finish restoration"],
    },
    "/projects/pond-mills-home-repairs/": {
        "name": "Pond Mills: One Repair List, A Much Closer Look",
        "description": "A Pond Mills home-repair project connecting new flooring and interior fixes with wet window areas, grading, downspout and exterior drainage work.",
        "image": "pond-mills-kitchen-floor-after.jpg",
        "image_alt": "Pond Mills kitchen after light plank flooring was installed beside oak cabinetry",
        "neighbourhood": "Pond Mills, London, Ontario",
        "status": "Completed",
        "services": ["Flooring and interior repairs", "Window-area moisture repairs", "Exterior grading and downspout work"],
    },
    "/projects/multi-unit-deck-renewal/": {
        "name": "Multi-Unit Deck Renewal",
        "description": "An anonymous London-area multi-unit deck project documented from weathered existing structures through framing and guard work to the completed exterior.",
        "image": "project-103.jpg",
        "image_alt": "Completed elevated wood decks behind an anonymous multi-unit property",
        "neighbourhood": "London area, Ontario",
        "status": "Completed",
        "services": ["Deck renewal", "Framing and support work", "Guards, railings and exterior carpentry"],
    },
}

PROJECTS = [
    ("melrose-bathroom-after.jpg", "bathrooms structural", "Completed Melrose-area bathroom with vanity, illuminated mirror and tiled shower", "Melrose bathroom", "Completed layout change"),
    ("melrose-wall-hung-toilet-progress.jpg", "bathrooms structural", "Wall-hung toilet installed during the Melrose-area bathroom renovation", "Melrose fixture progress", "Installation in progress"),
    ("melrose-shower-tile-progress.jpg", "bathrooms", "Dark wall tile being installed in the Melrose-area shower", "Melrose shower tile", "Tile installation"),
    ("melrose-shower-toilet-detail.jpg", "bathrooms", "Completed Melrose-area tiled shower and wall-hung toilet", "Melrose finish detail", "Completed bathroom"),
    ("melrose-exercise-room-finishing.jpg", "drywall handyman", "Ceiling and paint finishing underway in the Melrose-area exercise room", "Melrose exercise room progress", "Drywall and paint"),
    ("melrose-exercise-room-after.jpg", "basements drywall", "Completed Melrose-area exercise room with smooth ceiling and painted walls", "Melrose exercise room", "Completed lower level"),
    ("hyde-park-kitchen-after.jpg", "kitchens", "Wide view of the completed Hyde Park kitchen", "Hyde Park kitchen", "Completed renewal"),
    ("hyde-park-pantry-and-appliance-layout.jpg", "kitchens handyman", "New pantry and reconfigured appliance wall in the Hyde Park kitchen", "Hyde Park pantry", "Storage and layout"),
    ("hyde-park-sink-and-dishwasher.jpg", "kitchens handyman", "New sink, counter and dishwasher in the Hyde Park kitchen", "Hyde Park sink wall", "Kitchen finish"),
    ("hyde-park-kitchen-preparation.jpg", "kitchens handyman", "Hyde Park kitchen protected during the update", "Hyde Park preparation", "Room protection"),
    ("hyde-park-backsplash-installation.jpg", "kitchens", "Backsplash tile being installed in the Hyde Park kitchen", "Hyde Park backsplash", "Tile installation"),
    ("blackfriars-first-opening.jpg", "restoration drywall", "Small initial ceiling opening during the Blackfriars leak investigation", "Blackfriars first opening", "Investigation"),
    ("blackfriars-investigation.jpg", "restoration drywall", "Protected investigation work after the Blackfriars ceiling was opened further", "Blackfriars investigation", "Investigation in progress"),
    ("blackfriars-structural-concern.jpg", "restoration structural", "Exposed framing documented during the Blackfriars investigation", "Blackfriars framing", "Existing condition"),
    ("blackfriars-rebuild.jpg", "restoration drywall insulation structural", "Blackfriars room during framing, insulation and rebuilding work", "Blackfriars rebuild", "Rebuilding in progress"),
    ("blackfriars-restored-room.jpg", "restoration drywall", "Restored Blackfriars room with smooth ceiling and painted walls", "Blackfriars restored room", "Completed restoration"),
    ("medway-finished-room.jpg", "flooring handyman", "Completed Medway room with cool gray-brown plank flooring and finished baseboards", "Medway finished room", "Completed flooring"),
    ("medway-finished-floor-detail.jpg", "flooring", "Close view of the completed Medway plank flooring and clean edge detail", "Medway floor detail", "Completed flooring"),
    ("pond-mills-kitchen-floor-after.jpg", "flooring handyman restoration", "Pond Mills kitchen after light plank flooring was installed beside oak cabinetry", "Pond Mills kitchen floor", "Completed result"),
    ("pond-mills-basement-floor-after.jpg", "flooring basements handyman", "Pond Mills lower-level room after light plank flooring and baseboards were completed", "Pond Mills lower-level floor", "Completed result"),
    ("hilltop-kitchen-wide.jpg", "kitchens", "Wide view of the completed Hilltop kitchen and island", "Hilltop kitchen", "Completed kitchen"),
    ("hilltop-kitchen-range.jpg", "kitchens", "Hilltop kitchen range wall and white cabinetry", "Hilltop range wall", "Kitchen detail"),
    ("hilltop-lower-level.jpg", "basements flooring", "Completed Hilltop lower-level living area with fireplace", "Hilltop lower level", "Completed basement"),
    ("hilltop-staircase.jpg", "basements flooring", "Finished Hilltop staircase with dark railing", "Hilltop staircase", "Flooring and stairs"),
    ("hilltop-green-tile-before.jpg", "bathrooms", "Hilltop upstairs bathroom with its original green-tile tub surround", "Hilltop bathroom before", "Before renovation"),
    ("hilltop-green-tile-after.jpg", "bathrooms", "Hilltop upstairs bathroom with a rebuilt marble-look tub surround", "Hilltop bathroom after", "Completed result"),
    ("hilltop-basement-bathroom-before.jpg", "bathrooms basements", "Hilltop basement bathroom before the shower, ceiling and finish renewal", "Hilltop basement bath before", "Before renovation"),
    ("hilltop-basement-bathroom-wide.jpg", "bathrooms basements", "Completed Hilltop basement bathroom with white vanity and glass shower", "Hilltop basement bath after", "Completed result"),
    ("bathroom-glass-block-before.jpg", "bathrooms", "Bathroom with a jetted tub and glass-block window before conversion", "Jetted-tub layout", "Bathroom before"),
    ("bathroom-glass-block-demolition.jpg", "bathrooms", "Tiled jetted-tub platform partly removed during demolition", "Tub-platform demolition", "Work in progress"),
    ("bathroom-glass-block-open-wall.jpg", "bathrooms insulation", "Tub removed with wall insulation and floor framing exposed", "Bathroom wall opened", "Structural preparation"),
    ("bathroom-walnut-vanity-after.jpg", "bathrooms flooring", "Completed tub-to-shower conversion with a walnut vanity, gray tile and sliding glass door", "Glass-shower conversion", "Completed bathroom"),
    ("kitchenette-before-wide.jpg", "kitchens commercial", "Office kitchen before cabinetry and repair work", "Office kitchen before", "Before renovation"),
    ("kitchenette-wall-plumbing-stage.jpg", "kitchens commercial drywall", "Office kitchen wall opened for plumbing and repair access", "Office kitchen wall access", "Work in progress"),
    ("kitchenette-cabinet-installation.jpg", "kitchens commercial handyman", "New office kitchen cabinet boxes and fronts during installation", "Office cabinet installation", "Installation in progress"),
    ("kitchenette-after-wide.jpg", "kitchens commercial", "Completed office kitchen with walnut-look cabinets and gray counter", "Office kitchen after", "Completed kitchen"),
    ("westmount-transformation-demolition.jpg", "structural drywall", "Westmount main-floor demolition and layout changes in progress", "Westmount layout work", "Ongoing transformation"),
    ("westmount-transformation-blue-wall-flooring.jpg", "flooring structural", "Completed Westmount living-space phase with plank flooring, pot lights and a deep-blue feature wall", "Westmount completed phase", "Completed phase · project ongoing"),
    ("westmount-transformation-cabinet-install.jpg", "kitchens handyman", "Hekman Home Services crew installing kitchen cabinetry in the phased Westmount project", "Westmount cabinetry", "Kitchen in progress"),
    ("westmount-transformation-kitchen-current.jpg", "kitchens", "Current Westmount kitchen progress before the planned backsplash and final styling", "Westmount kitchen progress", "Work in progress"),
    ("westmount-porch-work-in-progress.jpg", "exterior handyman", "Exterior work in progress at an anonymous Westmount porch and entry", "Westmount porch progress", "Work in progress"),
    ("westmount-porch-after-night.jpg", "exterior handyman", "Finished Westmount porch and entry illuminated at night", "Westmount porch after", "Completed exterior"),
    ("project-016.jpg", "drywall", "Original textured ceiling and patch before smooth-ceiling work", "Popcorn ceiling before", "Before renovation"),
    ("project-017.jpg", "drywall", "Skim coating underway with the room protected", "Ceiling skim coat", "Surface preparation"),
    ("popcorn-ceiling-primer.jpg", "drywall", "Primer being rolled onto a smoothed ceiling", "Smooth ceiling primer", "Work in progress"),
    ("multi-unit-decks-before.jpg", "exterior", "Weathered elevated wood decks at an anonymous multi-unit property before renewal", "Multi-unit decks before", "Before renewal"),
    ("project-103.jpg", "exterior", "Completed elevated wood deck behind a brick home", "Elevated deck", "Completed exterior"),
    ("project-101.jpg", "exterior structural", "Deck framing and support-post structure", "Deck structure", "Structural preparation"),
    ("fence-after-1.jpg", "exterior", "Completed long-run wood privacy fence", "Privacy fence", "Completed exterior"),
    ("fence-post-auger-installation.jpg", "exterior", "Powered auger preparing a fence-post hole in a London residential yard", "Fence-post auger work", "Installation in progress"),
    ("fence-post-layout-progress.jpg", "exterior", "New wood fence posts aligned through a London front yard during installation", "Fence-post layout", "Installation in progress"),
    ("post-hole-digging.jpg", "exterior", "Post hole being dug by hand beside a residential property", "Post-hole preparation", "Site preparation"),
    ("post-hole-auger.jpg", "exterior", "Powered auger digging a post hole", "Powered auger work", "Site preparation"),
    ("project-045.jpg", "commercial", "Older box-style fluorescent fixtures before a fitness-space lighting upgrade", "Fitness lighting before", "Before upgrade"),
    ("project-049.jpg", "commercial", "Crew replacing commercial lighting from scaffolding and ladders", "Fitness lighting installation", "Installation in progress"),
    ("project-048.jpg", "commercial", "Fitness facility illuminated by the completed LED lighting upgrade", "Fitness lighting after", "Completed result"),
    ("salon-moisture-investigation.jpg", "restoration commercial", "Moisture meter documenting the affected trim area in an anonymous London salon", "Salon moisture check", "Investigation"),
    ("salon-wall-ceiling-rebuild.jpg", "restoration commercial drywall", "Wall and ceiling surfaces being rebuilt in an anonymous London salon", "Salon wall and ceiling rebuild", "Work in progress"),
    ("salon-restored-wall.jpg", "restoration commercial", "Completed wall repair in an anonymous London salon", "Salon wall restored", "Completed restoration"),
]
PROJECT_GALLERY_PRIORITY = (
    "melrose-bathroom-after.jpg",
    "hyde-park-kitchen-after.jpg",
    "blackfriars-restored-room.jpg",
    "medway-finished-room.jpg",
    "hilltop-kitchen-wide.jpg",
    "hilltop-lower-level.jpg",
    "bathroom-walnut-vanity-after.jpg",
    "kitchenette-after-wide.jpg",
    "westmount-transformation-blue-wall-flooring.jpg",
    "westmount-porch-after-night.jpg",
    "project-103.jpg",
    "fence-after-1.jpg",
    "project-048.jpg",
    "salon-restored-wall.jpg",
    "melrose-exercise-room-after.jpg",
    "medway-finished-floor-detail.jpg",
    "hilltop-green-tile-after.jpg",
    "hilltop-basement-bathroom-wide.jpg",
)
